### PR TITLE
iam_role_arn parameter

### PR DESCRIPTION
**Pull request by salemgolemugoo**
## what

A new iam_role_arn parameter is introduced
## why
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack#iam_role_arn

## references
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack#iam_role_arn

### CODE REVIEW

**Comment by hans-d** [comment]
@salemgolemugoo thanks. Can you follow up on the failing checks?

**Comment by salemgolemugoo** [comment]
Updated

**Comment by hans-d** [comment]
@salemgolemugoo and this one?
```
README.md is outdated. Please run the following commands locally and push the file:
  make init
  make readme
```

**Comment by salemgolemugoo** [comment]
Thanks for the help, updated docs as well

**Review by hans-d — APPROVED** [review]

**Comment by hans-d** [comment]
😿 
```
Error: creating CloudFormation Stack (eg-test-cloudformation-stack): ValidationError: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
	status code: 400, request id: ecf15321-c04a-4bd9-b120-26f[60](https://github.com/cloudposse/actions/actions/runs/8131761327/job/22221456703#step:9:61)e383560
  on ../../main.tf line 1, in resource "aws_cloudformation_stack" "default":
   1: resource "aws_cloudformation_stack" "default" {

}
    apply.go:15: 
        	Error Trace:	apply.go:15
        	            				examples_complete_test.go:27
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
        	            	Error: creating CloudFormation Stack (eg-test-cloudformation-stack): ValidationError: S3 error: Access Denied
        	            	For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
        	            		status code: 400, request id: ecf15321-c04a-4bd9-b120-26f60e383560
        	            	
        	            	  on ../../main.tf line 1, in resource "aws_cloudformation_stack" "default":
        	            	   1: resource "aws_cloudformation_stack" "default" {
        	            	
        	            	}
        	Test:       	TestExamplesComplete
```

neeeds to be looked into re this moduel (if you can assist that would be a big+), otherwise needs some involvement from out side ..

**Comment by hans-d** [comment]
@salemgolemugoo might take a bit of time to get the failing check working again (will be done in a separate pr once we have a bit more visibility on the cause/solution). As we have more places where this pops up, it might take a bit longer - but we keep track of things.

**Pull request closed without merging**
